version: "3.9"

services:
  gastos-familia:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app          # Para mapear todo el código y facilitar el desarrollo
      - db_data:/app/movimientos.db  # <--- Volumen separado para la base de datos
    container_name: gastos_familia_app

volumes:
  db_data:
