version: "3.9"

services:
  gastos-familia:
    build: .
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - .:/gestion_239               # ✅ Mapeado al mismo WORKDIR definido en el Dockerfile
      - ./data:/gestion_239/data     # ✅ Carpeta de datos persistente
    container_name: gestion_239
